version: '3.9'
services:
    web:
        build:
            context: .
            dockerfile: Dockerfile
        image: my-web
        ports:
            - '7003:5000'
        volumes:
            - ./templates:/app/templates
